background #0a0a0a
foreground #eeeeee
cursor #fab283
selection_background #1d1d25
selection_foreground #eeeeee
color0 #0a0a0a
color8 #808080
color1 #e06c75
color9 #e26a75
color2 #7fd88f
color10 #b8db87
color3 #f5a742
color11 #e5c07b
color4 #fab283
color12 #fab283
color5 #9d7cd8
color13 #9d7cd8
color6 #56b6c2
color14 #56b6c2
color7 #808080
color15 #eeeeee
