complete -c eops -f
complete -c eops -n '__fish_use_subcommand' -a go -d 'cd ke repo everyday-ops'
complete -c eops -n '__fish_use_subcommand' -a start -d 'generate daily log + todo'
complete -c eops -n '__fish_use_subcommand' -a todo -d 'lihat todo harian'
complete -c eops -n '__fish_use_subcommand' -a daily -d 'lihat daily log'
complete -c eops -n '__fish_use_subcommand' -a task -d 'quick add task tanpa refine'
complete -c eops -n '__fish_use_subcommand' -a ai -d 'smart add task (refine via claude -p)'
complete -c eops -n '__fish_seen_subcommand_from ai' -l raw -d 'bypass smart refine'
complete -c eops -n '__fish_seen_subcommand_from ai' -l smart -d 'paksa smart refine'
complete -c eops -n '__fish_use_subcommand' -a refine -d 'refine keseluruhan todo hari ini'
complete -c eops -n '__fish_use_subcommand' -a ctx -d 'lihat context ringkas'
complete -c eops -n '__fish_use_subcommand' -a bootstrap -d 'tampilkan bootstrap prompt model'
complete -c eops -n '__fish_use_subcommand' -a status -d 'cek status harian'
complete -c eops -n '__fish_use_subcommand' -a path -d 'lihat path root everyday-ops'
complete -c eops -n '__fish_use_subcommand' -a help -d 'bantuan'
