set -g status-position bottom
set -g default-terminal "tmux-256color"
set -g mouse on
set -g status-interval 2
set -g extended-keys on
set -g extended-keys-format csi-u
set -g allow-passthrough on
set -g base-index 1
set-option -g renumber-windows on

set -sg escape-time 0
set -g set-clipboard on

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send-keys -X copy-pipe "pbcopy"

bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded..."

bind -n M-t new-window -c "#{pane_current_path}"
bind -n M-T clock-mode
bind -n M-w choose-window
bind -n M-q send-keys C-c \; kill-pane

bind -n M-i if-shell -F '#{pane_in_mode}' 'send-keys q' 'copy-mode'

unbind -n C-h
unbind -n C-j
unbind -n C-k
unbind -n C-l
unbind -n M-v
unbind -n v

bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
vim_pattern='(\S+/)?g?\.?(view|l?n?vim?x?|fzf)(diff)?(-wrapped)?'
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +${vim_pattern}$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'
tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9
bind -n M-0 select-window -t 10

setenv -g TMUX_PLUGIN_MANAGER_PATH "$HOME/.tmux/plugins/"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'hendrikmi/tmux-cpu-mem-monitor'
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'

if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

run -b '~/.tmux/plugins/tpm/tpm'

gray_light="#c0caf5"
gray_medium="#414868"
gray_dark="#24283b"
green_soft="#9ece6a"
blue_muted="#7aa2f7"
cyan_soft="#7dcfff"
pink_soft="#bb9af7"
yellow_soft="#e0af68"

set -g status-left-length 100
set -g status-right-length 100
set -g status-style "fg=${gray_light},bg=${gray_dark}"
set -g window-status-separator ""

set -g status-left "#[fg=${gray_dark},bg=${pink_soft},bold]  #S "
set -g status-right "#[fg=${gray_dark},bg=${cyan_soft},bold]  #{cpu} #[fg=${gray_dark},bg=${green_soft}]  #{mem} "

set -g window-status-current-format "#[fg=${gray_dark},bg=${blue_muted},bold] #I:#W "
set -g window-status-format "#[fg=${gray_light},bg=${gray_medium}] #I:#W "

set -g message-style "fg=${cyan_soft},bg=default"
set -g mode-style "fg=${gray_dark},bg=${yellow_soft}"

set -g pane-border-style "fg=${gray_dark}"
set -g pane-active-border-style "fg=${blue_muted}"
