vim.cmd("hi clear")
if vim.fn.exists("syntax_on") == 1 then
    vim.cmd("syntax reset")
end

vim.o.termguicolors = true
vim.g.colors_name = "opencode"

local palettes = {
    dark = {
        bg = "#0a0a0a",
        panel = "#111111",
        element = "#171717",
        line = "#151515",
        border = "#202020",
        border_active = "#2b2b2b",
        visual = "#1d1d25",
        fg = "#eeeeee",
        muted = "#808080",
        primary = "#fab283",
        accent = "#9d7cd8",
        success = "#7fd88f",
        warning = "#f5a742",
        error = "#e06c75",
        info = "#56b6c2",
        type = "#e5c07b",
        diff_add = "#b8db87",
        diff_delete = "#e26a75",
        diff_add_bg = "#112018",
        diff_delete_bg = "#241217",
        ansi = {
            "#0a0a0a",
            "#e06c75",
            "#7fd88f",
            "#f5a742",
            "#fab283",
            "#9d7cd8",
            "#56b6c2",
            "#808080",
            "#808080",
            "#e26a75",
            "#b8db87",
            "#e5c07b",
            "#fab283",
            "#9d7cd8",
            "#56b6c2",
            "#eeeeee",
        },
    },
    light = {
        bg = "#ffffff",
        panel = "#f5f5f5",
        element = "#ebebeb",
        line = "#f3f3f3",
        border = "#dddddd",
        border_active = "#bdbdbd",
        visual = "#dfeaf7",
        fg = "#1a1a1a",
        muted = "#8a8a8a",
        primary = "#3b7dd8",
        accent = "#d68c27",
        success = "#3d9a57",
        warning = "#d68c27",
        error = "#d1383d",
        info = "#318795",
        type = "#b0851f",
        diff_add = "#4db380",
        diff_delete = "#f52a65",
        diff_add_bg = "#e7f6ed",
        diff_delete_bg = "#fde7ef",
        ansi = {
            "#1a1a1a",
            "#d1383d",
            "#3d9a57",
            "#d68c27",
            "#3b7dd8",
            "#d68c27",
            "#318795",
            "#8a8a8a",
            "#8a8a8a",
            "#f52a65",
            "#4db380",
            "#b0851f",
            "#3b7dd8",
            "#d68c27",
            "#318795",
            "#1a1a1a",
        },
    },
}

-- ponytail: OpenCode exposes the base palette, so the surface shades here are derived from it.
local palette = palettes[vim.o.background == "light" and "light" or "dark"]

local function hi(group, opts)
    vim.api.nvim_set_hl(0, group, opts)
end

local function link(group, target)
    hi(group, { link = target })
end

local groups = {
    ColorColumn = { bg = palette.line },
    Comment = { fg = palette.muted },
    Conceal = { fg = palette.muted },
    Constant = { fg = palette.warning },
    Cursor = { fg = palette.bg, bg = palette.primary },
    CursorColumn = { bg = palette.line },
    CursorLine = { bg = palette.line },
    CursorLineNr = { fg = palette.primary, bg = palette.line, bold = true },
    Delimiter = { fg = palette.fg },
    DiffAdd = { fg = palette.success, bg = palette.diff_add_bg },
    DiffChange = { fg = palette.warning, bg = palette.panel },
    DiffDelete = { fg = palette.error, bg = palette.diff_delete_bg },
    DiffText = { fg = palette.primary, bg = palette.element },
    DiagnosticError = { fg = palette.error },
    DiagnosticHint = { fg = palette.info },
    DiagnosticInfo = { fg = palette.info },
    DiagnosticOk = { fg = palette.success },
    DiagnosticSignError = { fg = palette.error, bg = palette.bg },
    DiagnosticSignHint = { fg = palette.info, bg = palette.bg },
    DiagnosticSignInfo = { fg = palette.info, bg = palette.bg },
    DiagnosticSignOk = { fg = palette.success, bg = palette.bg },
    DiagnosticSignWarn = { fg = palette.warning, bg = palette.bg },
    DiagnosticUnderlineError = { undercurl = true, sp = palette.error },
    DiagnosticUnderlineHint = { undercurl = true, sp = palette.info },
    DiagnosticUnderlineInfo = { undercurl = true, sp = palette.info },
    DiagnosticUnderlineWarn = { undercurl = true, sp = palette.warning },
    DiagnosticVirtualTextError = { fg = palette.error, bg = palette.panel },
    DiagnosticVirtualTextHint = { fg = palette.info, bg = palette.panel },
    DiagnosticVirtualTextInfo = { fg = palette.info, bg = palette.panel },
    DiagnosticVirtualTextWarn = { fg = palette.warning, bg = palette.panel },
    Directory = { fg = palette.primary },
    Error = { fg = palette.error, bold = true },
    ErrorMsg = { fg = palette.error },
    FloatBorder = { fg = palette.border_active, bg = palette.panel },
    FloatTitle = { fg = palette.primary, bg = palette.panel, bold = true },
    FoldColumn = { fg = palette.muted, bg = palette.bg },
    Folded = { fg = palette.muted, bg = palette.panel },
    Function = { fg = palette.primary },
    Identifier = { fg = palette.error },
    IncSearch = { fg = palette.bg, bg = palette.accent },
    Keyword = { fg = palette.accent },
    LineNr = { fg = palette.muted },
    MatchParen = { fg = palette.info, bold = true, underline = true },
    ModeMsg = { fg = palette.fg, bold = true },
    MoreMsg = { fg = palette.success },
    NonText = { fg = palette.border_active },
    Normal = { fg = palette.fg, bg = palette.bg },
    NormalFloat = { fg = palette.fg, bg = palette.panel },
    NormalNC = { fg = palette.fg, bg = palette.bg },
    Number = { fg = palette.primary },
    Operator = { fg = palette.info },
    Pmenu = { fg = palette.fg, bg = palette.panel },
    PmenuSbar = { bg = palette.element },
    PmenuSel = { fg = palette.bg, bg = palette.primary },
    PmenuThumb = { bg = palette.muted },
    PreProc = { fg = palette.warning },
    Question = { fg = palette.info },
    QuickFixLine = { bg = palette.visual },
    Search = { fg = palette.bg, bg = palette.primary },
    SignColumn = { bg = palette.bg },
    Special = { fg = palette.info },
    SpecialComment = { fg = palette.muted },
    SpecialKey = { fg = palette.muted },
    Statement = { fg = palette.accent },
    StatusLine = { fg = palette.fg, bg = palette.panel },
    StatusLineNC = { fg = palette.muted, bg = palette.panel },
    String = { fg = palette.success },
    Substitute = { fg = palette.bg, bg = palette.warning },
    TabLine = { fg = palette.muted, bg = palette.panel },
    TabLineFill = { bg = palette.panel },
    TabLineSel = { fg = palette.fg, bg = palette.element, bold = true },
    Title = { fg = palette.primary, bold = true },
    Todo = { fg = palette.bg, bg = palette.warning, bold = true },
    Type = { fg = palette.type },
    Underlined = { fg = palette.info, underline = true },
    VertSplit = { fg = palette.border },
    Visual = { bg = palette.visual },
    WarningMsg = { fg = palette.warning },
    WinSeparator = { fg = palette.border },
    Boolean = { fg = palette.primary },
    Character = { fg = palette.success },
    CurSearch = { fg = palette.bg, bg = palette.accent },
    EndOfBuffer = { fg = palette.bg },
    Float = { fg = palette.primary },
    lCursor = { fg = palette.bg, bg = palette.primary },
    TermCursor = { fg = palette.bg, bg = palette.primary },
}

for group, opts in pairs(groups) do
    hi(group, opts)
end

local links = {
    ["@boolean"] = "Boolean",
    ["@character"] = "Character",
    ["@comment"] = "Comment",
    ["@comment.documentation"] = "Comment",
    ["@constant"] = "Constant",
    ["@constructor"] = "Type",
    ["@function"] = "Function",
    ["@function.builtin"] = "Function",
    ["@keyword"] = "Keyword",
    ["@keyword.function"] = "Keyword",
    ["@markup.heading"] = "Title",
    ["@markup.link"] = "Underlined",
    ["@markup.raw"] = "String",
    ["@method"] = "Function",
    ["@module"] = "Type",
    ["@namespace"] = "Type",
    ["@number"] = "Number",
    ["@operator"] = "Operator",
    ["@property"] = "Special",
    ["@punctuation.bracket"] = "Delimiter",
    ["@punctuation.delimiter"] = "Delimiter",
    ["@string"] = "String",
    ["@tag"] = "Keyword",
    ["@tag.attribute"] = "Special",
    ["@type"] = "Type",
    ["@type.builtin"] = "Type",
    ["@variable"] = "Identifier",
    ["@variable.builtin"] = "Special",
    BlinkCmpDoc = "NormalFloat",
    BlinkCmpDocBorder = "FloatBorder",
    BlinkCmpMenu = "Pmenu",
    BlinkCmpMenuBorder = "FloatBorder",
    BlinkCmpMenuSelection = "PmenuSel",
    LazyNormal = "NormalFloat",
    LspReferenceRead = "Visual",
    LspReferenceText = "Visual",
    LspReferenceWrite = "Visual",
    MasonNormal = "NormalFloat",
    NeoTreeFloatBorder = "FloatBorder",
    NeoTreeNormal = "NormalFloat",
    NeoTreeNormalNC = "NormalFloat",
    NoiceCmdlinePopupBorder = "FloatBorder",
    NoicePopupBorder = "FloatBorder",
    TelescopeBorder = "FloatBorder",
    TelescopeNormal = "NormalFloat",
    TelescopePreviewTitle = "FloatTitle",
    TelescopePromptBorder = "FloatBorder",
    TelescopePromptNormal = "NormalFloat",
    TelescopePromptTitle = "FloatTitle",
    TelescopeResultsTitle = "FloatTitle",
    VisualNOS = "Visual",
    WhichKeyFloat = "NormalFloat",
    WildMenu = "PmenuSel",
}

for group, target in pairs(links) do
    link(group, target)
end

for index, color in ipairs(palette.ansi) do
    vim.g["terminal_color_" .. (index - 1)] = color
end
